### ISSUE TITLE
todo for v0.1

### ISSUE THREAD

**Issue by dansup** [pixelfedLabs/state#1]
- [ ] Update readme with installation instructions
- [ ] finish ActivityPub integration
- [x] Add Atom feeds for every service
